# Site settings
name: Graham Felton
title: Graham Felton | Computational Designer
description: Designer, coder, and thinker at Carnegie Mellon University
url: https://1gfelton.github.io/
baseurl: ''
email: gtf@andrew.cmu.com
cover: https://gfelton.github.io/img/og.png
logo: https://gfelton.github.io/img/emojis/technologist.png
resume: https://gfelton.github.io/resume.pdf
social:
  - title: email
    url: mailto:gtf@andrew.cmu.com
  - title: twitter
    url: https://twitter.com/bchiang7
  - title: instagram
    url: https://instagram.com/bchiang7
  - title: codepen
    url: http://codepen.io/bchiang7
  - title: github
    url: https://github.com/1gfelton
  - title: linkedin
    url: https://www.linkedin.com/in/graham-felton-a59891271/

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
